export default {
  modalsVisibility: {
    Menu: false,
    AddSectionModal: false,
    EditSectionModal: false,
    DeleteSectionDialog: false,
    AddGroupModal: false,
    EditGroupModal: false,
    SearchModal: false,
    DeleteGroupDialog: false,
    AddCardModal: false,
    RevisionDialog: false,
    Revision: false,
    GroupChart: false,
    DictionaryModal: false,
    EditCardModal: false,
    DeleteCardDialog: false,
    ErrorModal: false,
  },
  sections: {
    active: 'ALL',
    items: [],
  },
  groups: {
    isFetching: false,
    filterWeakGroups: true,
    active: false,
    items: [],
  },
  cards: {
    isFetching: false,
    active: false,
    items: [],
    deleteCards: [],
  },
  revision: {
    position: 1,
    revisionDuration: 0,
  },
  reforceCards: {
    items: [],
  },
  error: '',
  tagsSuggestion: [
    'verb',
    'noun',
    'adjective',
    'adverb',
    'abstract',
    'past',
    'collective',
    'concrete',
    'irregular verb',
    'derivative',
    'primitive',
    'simple',
    'male',
    'fem.',
    'unusual translation',
    'phrase',
    'informal',
    'less formal',
    "isn't so obvious",
    'transitive',
    'intransitive',
    'idioms',
    'phrasal verb',
  ],
};
